---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    assignees:
      - "lishaduck"
    groups:
      lint:
        patterns:
          - "@sherifforg/*"
          - "eslint*"
      commitlint:
        patterns:
          - "@commitlint/*"
      build:
        patterns:
          - "vite*"
          - "@vitest/*"
          - "@vite-pwa/*"
          - "workbox*"
          - "browserslist*"
          - "lightningcss"
          - "turbo"
      fontawesome:
        patterns:
          - "@fortawesome/*"
      zod:
        patterns:
          - "zod*"
      storybook:
        patterns:
          - "@storybook/"
          - "storybook"
          - "@chromatic-com/storybook"
          - "chromatic"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "lishaduck"
    groups:
      github-actions:
        patterns:
          - "actions/*"
