autoInstallPeers: false
strictPeerDependencies: true
disallowWorkspaceCycles: true
engineStrict: true

peerDependencyRules:
  allowAny:
    - eslint

onlyBuiltDependencies:
  - esbuild
  - sharp

ignoredBuiltDependencies:
  - eslint-config-sheriff
  - mws
  - svelte-preprocess

overrides:
  vitest>jsdom: "-"

patchedDependencies:
  eslint-config-sheriff: patches/eslint-config-sheriff.patch

packages:
  - apps/*
  - packages/*

catalog:
  "@chromatic-com/storybook": ^3.2.6
  "@codemirror/autocomplete": ^6.18.6
  "@codemirror/commands": ^6.8.0
  "@codemirror/language": ^6.11.0
  "@codemirror/language-data": ^6.5.1
  "@codemirror/lang-markdown": ^6.3.2
  "@codemirror/search": ^6.5.10
  "@codemirror/state": ^6.5.2
  "@codemirror/view": ^6.36.4
  "@commitlint/cli": ^19.8.0
  "@commitlint/config-conventional": ^19.8.0
  "@cspell/eslint-plugin": ^8.17.5
  "@fortawesome/fontawesome-svg-core": ^6.7.2
  "@fortawesome/free-solid-svg-icons": ^6.7.2
  "@lezer/highlight": ^1.2.1
  "@lezer/markdown": ^1.4.2
  "@lezer-unofficial/printer": ^1.0.1
  "@manypkg/cli": ^0.23.0
  "@storybook/addon-a11y": ^8.6.7
  "@storybook/addon-designs": ^8.2.1
  "@storybook/addon-essentials": ^8.6.7
  "@storybook/addon-svelte-csf": =5.0.0-next.28
  "@storybook/blocks": ^8.6.7
  "@storybook/experimental-addon-test": ^8.6.7
  "@storybook/svelte": ^8.6.7
  "@storybook/sveltekit": ^8.6.7
  "@storybook/test": ^8.6.7
  "@sveltejs/adapter-static": ^3.0.8
  "@sveltejs/kit": ^2.20.1
  "@sveltejs/vite-plugin-svelte": ^5.0.3
  "@tailwindcss/forms": ^0.5.10
  "@tailwindcss/typography": ^0.5.16
  "@tailwindcss/vite": ^4.0.14
  "@total-typescript/ts-reset": ^0.6.1
  "@types/pathfinding": ~0.0.9
  "@types/react": ~18.3.18
  "@vite-pwa/assets-generator": ^0.2.6
  "@vitest/browser": ^3.0.9
  "@vitest/coverage-v8": ^3.0.9
  browserslist: ^4.24.4
  browserslist-to-esbuild: ^2.1.1
  chromatic: ^11.27.0
  codemirror: ^6.0.1
  eslint: ^9.22.0
  eslint-config-sheriff: ^27.0.0
  eslint-plugin-perfectionist: ^4.10.1
  eslint-plugin-svelte: ^3.3.2
  fontaine: ^0.5.0
  globals: ^16.0.0
  html-template-tag: ^4.1.1
  husky: ^9.1.7
  hypermd: https://pkg.pr.new/jsimonrichard/HyperMD/hypermd@7a49f4a
  idb-keyval: ^6.2.1
  jiti: ^2.4.2
  knip: ^5.46.0
  lightningcss: ^1.29.3
  loro-codemirror: ^0.1.6
  loro-crdt: ^1.4.6
  pathfinding: ^0.4.18
  playwright: ^1.51.1
  prettier-plugin-svelte: ^3.3.3
  prettier-plugin-tailwindcss: ^0.6.11
  prettier: 3.5.3
  storybook: ^8.6.7
  svelte: ^5.23.2
  svelte-check: ^4.1.5
  svelte-codemirror-editor: ^1.4.1
  svelte2tsx: ^0.7.35
  tailwindcss: ^4.0.14
  turbo: ^2.4.4
  typed-query-selector: ^2.12.0
  typescript: ~5.8.2
  typescript-eslint-parser-for-extra-files: ^0.7.0
  typesync: ^0.14.1
  uint8array-extras: ^1.4.0
  unstorage: ^1.15.0
  vite: ^6.2.2
  vite-plugin-html-minifier: ^1.0.5
  vite-plugin-pwa: ^0.21.1
  vite-plugin-top-level-await: ^1.5.0
  vite-plugin-wasm: ^3.4.1
  vite-plugin-webfont-dl: ^3.10.4
  vitest-browser-svelte: ^0.1.0
  vitest: ^3.0.9
  workbox-build: ^7.3.0
  workbox-core: ^7.3.0
  workbox-precaching: ^7.3.0
  workbox-window: ^7.3.0
  zod: ^3.24.2
  zod-validation-error: ^3.4.0
