packages:
  - apps/*
  - packages/*
catalog:
  "@chromatic-com/storybook": ^3.2.4
  "@codemirror/autocomplete": ^6.18.6
  "@codemirror/commands": ^6.8.0
  "@codemirror/language": ^6.10.8
  "@codemirror/language-data": ^6.5.1
  "@codemirror/lang-markdown": ^6.3.2
  "@codemirror/search": ^6.5.9
  "@codemirror/state": ^6.5.1
  "@codemirror/view": ^6.36.2
  "@cspell/eslint-plugin": ^8.17.3
  "@fortawesome/fontawesome-svg-core": ^6.7.2
  "@fortawesome/free-solid-svg-icons": ^6.7.2
  "@lezer/highlight": ^1.2.1
  "@lezer/markdown": ^1.4.1
  "@lezer-unofficial/printer": ^1.0.1
  "@storybook/addon-a11y": ^8.5.6
  "@storybook/addon-designs": ^8.2.0
  "@storybook/addon-essentials": ^8.5.6
  "@storybook/addon-svelte-csf": =5.0.0-next.23
  "@storybook/blocks": ^8.5.6
  "@storybook/experimental-addon-test": ^8.5.6
  "@storybook/svelte": ^8.5.6
  "@storybook/sveltekit": ^8.5.6
  "@storybook/test": ^8.5.6
  "@sveltejs/adapter-static": ^3.0.8
  "@sveltejs/kit": ^2.17.2
  "@sveltejs/vite-plugin-svelte": ^5.0.3
  "@tailwindcss/forms": ^0.5.10
  "@tailwindcss/typography": ^0.5.16
  "@tailwindcss/vite": ^4.0.6
  "@total-typescript/ts-reset": ^0.6.1
  "@types/pathfinding": ~0.0.9
  "@types/react": ~18.3.18
  "@vite-pwa/assets-generator": ^0.2.6
  "@vitest/browser": ^3.0.5
  "@vitest/coverage-v8": ^3.0.5
  browserslist: ^4.24.4
  browserslist-to-esbuild: ^2.1.1
  chromatic: ^11.25.2
  codemirror: ^6.0.1
  eslint: ^9.20.1
  eslint-config-sheriff: ^25.8.1
  eslint-plugin-perfectionist: ^4.9.0
  eslint-plugin-svelte: =3.0.0-next.16
  fontaine: ^0.5.0
  globals: ^15.15.0
  html-template-tag: ^4.1.1
  hypermd: https://pkg.pr.new/jsimonrichard/HyperMD/hypermd@9c02ff2
  idb-keyval: ^6.2.1
  jiti: ^2.4.2
  lightningcss: ^1.29.1
  pathfinding: ^0.4.18
  playwright: ^1.50.1
  storybook: ^8.5.6
  svelte: ^5.20.1
  svelte-check: ^4.1.4
  svelte-codemirror-editor: ^1.4.1
  svelte2tsx: ^0.7.34
  tailwindcss: ^4.0.6
  typed-query-selector: ^2.12.0
  typescript: ~5.7.3
  typescript-eslint-parser-for-extra-files: ^0.7.0
  unstorage: ^1.14.4
  vite: ^6.1.0
  vite-plugin-html-minifier: ^1.0.5
  vite-plugin-pwa: ^0.21.1
  vite-plugin-webfont-dl: ^3.10.4
  vitest-browser-svelte: ^0.1.0
  vitest: ^3.0.5
  workbox-build: ^7.3.0
  workbox-core: ^7.3.0
  workbox-precaching: ^7.3.0
  workbox-window: ^7.3.0
  zod: ^3.24.2
  zod-validation-error: ^3.4.0
