autoInstallPeers: false
strictPeerDependencies: true
disallowWorkspaceCycles: true
engineStrict: true
strictDepBuilds: true
shellEmulator: true
verifyDepsBeforeRun: warn
enablePrePostScripts: false
ignorePatchFailures: false
enableGlobalVirtualStore: true
catalogMode: strict

hoist: false

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - sharp

ignoredBuiltDependencies:
  - msw

peerDependencyRules:
  allowedVersions:
    eslint: ^9.0.0

packageExtensions:
  "@vitest/browser":
    peerDependencies:
      vite: "*"

  vite-plugin-top-level-await:
    peerDependencies:
      rollup: "*"

  "storybook":
    peerDependencies:
      "@chromatic-com/storybook": "*"
      "@storybook/addon-a11y": "*"
      "@storybook/addon-designs": "*"
      "@storybook/addon-docs": "*"
      "@storybook/addon-svelte-csf": "*"
      "@storybook/addon-vitest": "*"
      "@storybook/sveltekit": "*"
    peerDependenciesMeta:
      "@storybook/sveltekit":
        optional: true
      "@storybook/addon-svelte-csf":
        optional: true
    dependencies:
      react: "^19.1.0"
      react-dom: "^19.1.0"

  "@storybook/svelte":
    dependencies:
      ts-dedent: ^2.0.0

  svelte-codemirror-editor:
    peerDependencies:
      "@codemirror/commands": "*"
      "@codemirror/language": "*"
      "@codemirror/state": "*"
      "@codemirror/view": "*"

  "@sveltejs/kit":
    peerDependencies:
      "typescript": "*"
    peerDependenciesMeta:
      typescript:
        optional: true

  "eslint-config-sheriff":
    dependencies:
      "@typescript-eslint/utils": "*"

patchedDependencies:
  eslint-config-sheriff: patches/eslint-config-sheriff.patch

packages:
  - apps/*
  - packages/*

catalog:
  "@chromatic-com/storybook": ^4.1.1
  "@codemirror/autocomplete": ^6.18.7
  "@codemirror/commands": ^6.8.1
  "@codemirror/language": ^6.11.3
  "@codemirror/language-data": ^6.5.1
  "@codemirror/lang-markdown": ^6.3.4
  "@codemirror/search": ^6.5.11
  "@codemirror/state": ^6.5.2
  "@codemirror/view": ^6.38.3
  "@commitlint/cli": ^19.8.1
  "@commitlint/config-conventional": ^19.8.1
  "@cspell/eslint-plugin": ^8.17.5
  "@fortawesome/fontawesome-svg-core": ^6.7.2
  "@fortawesome/free-solid-svg-icons": ^6.7.2
  "@lezer/highlight": ^1.2.1
  "@lezer/markdown": ^1.4.3
  "@lezer-unofficial/printer": ^1.0.1
  "@manypkg/cli": ^0.25.0
  "@storybook/addon-a11y": ^9.1.8
  "@storybook/addon-designs": ^10.0.2
  "@storybook/addon-docs": ^9.1.8
  "@storybook/addon-svelte-csf": ^5.0.7
  "@storybook/addon-vitest": ^9.1.8
  "@storybook/sveltekit": ^9.1.8
  "@sveltejs/adapter-static": ^3.0.9
  "@sveltejs/kit": ^2.28.0
  "@sveltejs/vite-plugin-svelte": ^5.1.1
  "@tailwindcss/forms": ^0.5.10
  "@tailwindcss/typography": ^0.5.16
  "@tailwindcss/vite": ^4.0.14
  "@total-typescript/ts-reset": ^0.6.1
  "@types/pathfinding": ~0.1.0
  "@types/react": ~19.1.10
  "@vite-pwa/assets-generator": ^0.2.6
  "@vitest/browser": ^3.2.4
  "@vitest/coverage-v8": ^3.2.4
  "@vitest/ui": ^3.2.4
  chromatic: ^13.2.0
  codemirror: ^6.0.2
  eslint: ^9.22.0
  eslint-config-sheriff: ^27.0.0
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-svelte: ^3.3.2
  fontaine: ^0.6.0
  globals: ^16.0.0
  html-template-tag: ^4.1.1
  husky: ^9.1.7
  hypermd: https://pkg.pr.new/jsimonrichard/HyperMD/hypermd@7a49f4a
  idb-keyval: ^6.2.2
  jiti: ^2.5.1
  knip: ^5.46.0
  lightningcss: ^1.29.3
  loro-codemirror: ^0.1.6
  loro-crdt: ^1.4.6
  pathfinding: ^0.4.18
  playwright: ^1.53.1
  prettier-plugin-svelte: ^3.3.3
  prettier-plugin-tailwindcss: ^0.6.14
  prettier: "3.5.3"
  storybook: ^9.1.8
  svelte: ^5.34.8
  svelte-check: ^4.2.2
  svelte-codemirror-editor: ^1.4.2
  svelte2tsx: ^0.7.43
  tailwindcss: ^4.0.14
  turbo: ^2.5.7
  typed-query-selector: ^2.12.0
  typescript: ~5.8.2
  typescript-eslint-parser-for-extra-files: ^0.7.0
  typesync: ^0.14.3
  uint8array-extras: ^1.5.0
  unstorage: ^1.15.0
  vite: ^6.3.6
  vite-plugin-html-minifier: ^1.0.5
  vite-plugin-pwa: ^0.21.2
  vite-plugin-top-level-await: ^1.5.0
  vite-plugin-wasm: ^3.4.1
  vite-plugin-webfont-dl: ^3.10.4
  vitest-browser-svelte: ^1.0.0
  vitest: ^3.2.4
  workbox-build: ^7.3.0
  workbox-core: ^7.3.0
  workbox-precaching: ^7.3.0
  workbox-window: ^7.3.0
  zod: ^3.24.2
  zod-validation-error: ^3.4.0
